var Site = {
	lang: "en", 
	locale: "en_US",
	archives: {}
};

Site.archives.posts = [
	{url: "/en/blog/2021/10/19/calc-card/", title: "Calculation card app for first graders released"},
	{url: "/en/blog/2016/01/18/space-travel-animated-gif/", title: "Space travel animated GIF generated by Golang"},
	{url: "/en/blog/2016/01/07/go-animated-gif-gen/", title: "Generate an animated GIF with Golang"},
	{url: "/en/blog/2015/12/31/go-image-gen/", title: "Generate an image programmatically with Golang"},
	{url: "/en/blog/2014/02/25/jenkins-home-win/", title: "Jenkins: How to change JENKINS_HOME on Windows"}
];

Site.archives.months = [
  "202110"
, "201601"
, "201512"
, "201402"
, "201401"
, "201311"
, "201310"
, "201307"
, "201306"
, "201305"
, "201304"
, "201303"
, "201302"
, "200904"
, "200903"
, "200902"
, "200806"
, "200805"
, "200801"
];